// Owner programı — hocadan gelen 4 günlük program, spec Ek-A'dan BİREBİR.
// (agents/03-stratejist/outputs/2026-06-13_formcoach-program-mode-spec.md)
//
// KURAL: coachNote alanları hocanın PDF'teki cümlelerinin kelimesi kelimesine
// kopyasıdır — kısaltılamaz, "iyileştirilemez", çevrilemez. Kurala çevrilen
// uyarılar AYRICA ruleSet içinde yaşar; not silinmez.
//
// Şema dokümantasyonu: src/programs/SCHEMA.md

// Kardiyo sonrası plank finisher'ı — generalRules.plank: haftada 3 gün, 3 set,
// "durabildiğin kadar" (izometrik süre tutma, hold dozu). Pose-takipli (P0):
// holdEngine geçerli plank pozisyonunu sayar, hipSag/hipPike form kurallarını uygular.
// 3 antrenman gününe (day1/day2/day4) eklenir → haftada 3 gün kuralı.
function plankFinisher(suffix) {
  return {
    type: "finisher",
    label: "Bitiriş — Plank",
    exercises: [
      {
        id: `plank-${suffix}`,
        name: "Plank",
        coachNote: "Kalça düşmesin, karın sık, omuz-kalça-ayak tek hat",
        videoUrl: null,
        embeddable: false,
        sets: 3,
        // İzometrik: sabit hedef yok ("durabildiğin kadar"); süre kaydedilir.
        dose: { type: "hold" },
        restSec: [30, 45],
        trackable: true,
        trackingPhase: "P0",
        ruleSetRef: "plank",
        untrackableReason: null,
      },
    ],
  };
}

export const ownerProgram = {
  id: "owner-coach-2026-06",
  name: "Hoca Programı",
  source: "coach-pdf",
  version: 1,
  generalRules: {
    cardio: { trainingDayMin: 30, restDayMin: 40, hrBpm: [110, 130] },
    plank: { perWeek: 3, sets: 3, mode: "max", after: "cardio" },
    defaultRestSec: [60, 90],
    negativeTempoSec: [2, 3],
    daysFlexible: true,
  },
  days: [
    // ─────────────── ANTRENMAN 1 — Pazartesi ───────────────
    {
      id: "day1", label: "Antrenman 1", suggestedDay: "Pazartesi",
      blocks: [
        { type: "warmup", label: "Isınma", exercises: [
          { id: "jumping-jack", name: "Jumping Jack",
            coachNote: null,
            videoUrl: "https://www.youtube.com/watch?v=czMg1_idVcg", embeddable: true,
            sets: 1, dose: { type: "time", seconds: 45 },
            trackable: true, trackingPhase: "P0", ruleSetRef: "jumpingJack", untrackableReason: null },
          { id: "bw-squat-warmup", name: "Bodyweight Squat",
            coachNote: null,
            videoUrl: "https://www.youtube.com/watch?v=EdgOc-sbddA", embeddable: true,
            sets: 1, dose: { type: "reps", value: 15 },
            trackable: true, trackingPhase: "P0", ruleSetRef: "squat", untrackableReason: null },
          { id: "band-pull-apart", name: "Band Pull Apart",
            coachNote: null,
            videoUrl: "https://www.youtube.com/shorts/SuvO4TBwSu4", embeddable: true,
            sets: 1, dose: { type: "reps", value: 20 },
            trackable: false, trackingPhase: null, ruleSetRef: null,
            untrackableReason: "Düşük genlikli bant hareketi — sinyal pose gürültü bandının içinde kalır." },
          { id: "standing-knee-raise", name: "Standing Knee Raise",
            coachNote: null,
            videoUrl: "https://www.youtube.com/watch?v=O_8EUJ7i-PI", embeddable: true,
            sets: 1, dose: { type: "perSide", value: 12 },
            trackable: true, trackingPhase: "P0", ruleSetRef: "kneeRaise", untrackableReason: null },
        ]},
        { type: "superset", label: "Superset A", rounds: 4,
          restBetweenExercisesSec: 0, restAfterRoundSec: 50, exercises: [
          { id: "lunge-lateral", name: "Lunge + Shoulder Dumbbell Lateral",
            coachNote: "Lunge'da diz asla öne fırlamasın, gövde hafif öne eğilsin",
            videoUrl: "https://www.youtube.com/watch?v=Tc-9yvl5Zt8", embeddable: false,
            sets: 4, dose: { type: "reps", value: 12 },
            // Combo: tek FSM bir ana hareket sayar → LUNGE sayılır (alt-gövde genliği
            // daha güvenilir); lateral kol ikincil (çift sayım riski yok). lateralRaise
            // motoru ayrıca kütüphanede tek başına takipli (Batch 3 P0).
            trackable: true, trackingPhase: "P0", ruleSetRef: "lunge", untrackableReason: null },
          { id: "squat-press", name: "Squat + Shoulder Dumbbell Press",
            coachNote: "Press'te dirsekleri çok açma, biraz öne al",
            videoUrl: "https://www.youtube.com/watch?v=0RAzZhXnsww", embeddable: false,
            sets: 4, dose: { type: "reps", value: 12 },
            // Combo: tek FSM bir ana hareket sayar → SQUAT sayılır (alt-gövde genliği
            // press kolundan güvenilir); press ikincil. shoulderPress motoru ayrıca
            // kütüphanede tek başına takipli (Batch 3 P0).
            trackable: true, trackingPhase: "P0", ruleSetRef: "squat",
            untrackableReason: null },
          { id: "push-up", name: "Push Up",
            coachNote: "Eller göğüs hizasında, boyun kırılmasın, karın sık",
            videoUrl: "https://www.youtube.com/watch?v=tmtgHxtyTkE", embeddable: true,
            sets: 4, dose: { type: "reps", value: 12 },
            trackable: true, trackingPhase: "P0", ruleSetRef: "pushup", untrackableReason: null },
        ]},
        { type: "superset", label: "Superset B", rounds: 4,
          restBetweenExercisesSec: 0, restAfterRoundSec: 60, exercises: [
          { id: "cg-lat-pulldown", name: "Close Grip Lat Pulldown",
            coachNote: "Eller omuz genişliği, barı göğsün üstüne çek",
            videoUrl: "https://www.youtube.com/watch?v=T2h4QVoV3r4", embeddable: true,
            sets: 4, dose: { type: "reps", value: 12 },
            trackable: false, trackingPhase: null, ruleSetRef: null,
            untrackableReason: "Kablo istasyonunda oturuş + ekipman öklüzyonu pose'u güvenilmez kılar." },
          { id: "rev-seated-cable-row", name: "Reverse Seated Cable Row",
            coachNote: "Gövdeyi sallama, dirsekleri yana değil arkaya sür",
            videoUrl: "https://www.youtube.com/watch?v=bQ9mCeNF0ok", embeddable: true,
            sets: 4, dose: { type: "reps", value: 12 },
            trackable: false, trackingPhase: null, ruleSetRef: null,
            untrackableReason: "Oturuşlu kablo çekişi — gövde/kol örtüşmesi ve makine öklüzyonu." },
        ]},
        { type: "superset", label: "Superset C", rounds: 4,
          restBetweenExercisesSec: 0, restAfterRoundSec: 50, exercises: [
          { id: "incline-db-bench", name: "Incline Dumbbell Bench Press",
            coachNote: "Dirsek 45°, üstte birleştirme, sık 1sn bekle",
            videoUrl: "https://www.youtube.com/watch?v=oAHFF8wziy0", embeddable: true,
            sets: 4, dose: { type: "reps", value: 12 },
            trackable: false, trackingPhase: null, ruleSetRef: null,
            untrackableReason: "Eğimli bench'e yatış — sırtüstü pozlarda pose modeli güvenilmez." },
          { id: "incline-db-curl", name: "Incline Dumbbell Curl",
            coachNote: "Dirsek sabit, her negatif 3 saniye",
            videoUrl: "https://www.youtube.com/watch?v=Jj8V5sSooTE", embeddable: true,
            sets: 4, dose: { type: "reps", value: 12 },
            trackable: false, trackingPhase: null, ruleSetRef: null,
            untrackableReason: "Bench yaslamalı oturuş — gövde landmark'ları örtülü." },
          { id: "vbar-pushdown", name: "V-Bar Push Down",
            coachNote: "Dirsekler gövdeye kilitli, aşağıda bileği kırma",
            videoUrl: "https://www.youtube.com/watch?v=j4nBkDprNAM", embeddable: true,
            sets: 4, dose: { type: "reps", value: 12 },
            trackable: false, trackingPhase: null, ruleSetRef: null,
            untrackableReason: "Kablo istasyonuna yakın duruş + bilek detayı landmark çözünürlüğünün altında." },
        ]},
        plankFinisher("d1"),
      ],
    },
    // ─────────────── ANTRENMAN 2 — Çarşamba ───────────────
    {
      id: "day2", label: "Antrenman 2", suggestedDay: "Çarşamba",
      blocks: [
        { type: "warmup", label: "Isınma", exercises: [
          { id: "band-ext-rot", name: "Band External Rotation", coachNote: null,
            videoUrl: "https://www.youtube.com/shorts/7DqYesMRkzU", embeddable: true,
            sets: 1, dose: { type: "reps", value: 20 }, trackable: false, trackingPhase: null,
            ruleSetRef: null, untrackableReason: "Düşük genlikli bant rotasyonu — pose çözünürlüğünün altında." },
          { id: "band-int-rot", name: "Band Internal Rotation", coachNote: null,
            videoUrl: "https://www.youtube.com/shorts/5n10NSwfp2U", embeddable: true,
            sets: 1, dose: { type: "reps", value: 20 }, trackable: false, trackingPhase: null,
            ruleSetRef: null, untrackableReason: "Düşük genlikli bant rotasyonu — pose çözünürlüğünün altında." },
          { id: "band-pull-apart-2", name: "Band Pull Apart", coachNote: null,
            videoUrl: "https://www.youtube.com/shorts/SuvO4TBwSu4", embeddable: true,
            sets: 1, dose: { type: "reps", value: 20 }, trackable: false, trackingPhase: null,
            ruleSetRef: null, untrackableReason: "Düşük genlikli bant hareketi." },
          { id: "prone-y-raise", name: "Prone Y Raise", coachNote: null,
            videoUrl: "https://www.youtube.com/watch?v=w1AWGKubE5U", embeddable: true,
            sets: 1, dose: { type: "reps", value: 20 }, trackable: false, trackingPhase: null,
            ruleSetRef: null, untrackableReason: "Yüzüstü pozisyon — pose modeli prone pozda güvenilmez." },
        ]},
        { type: "straight", label: "Ana Antrenman", exercises: [
          { id: "machine-fly", name: "Machine Fly",
            coachNote: "dirsek açısı kilitli, kapanışta 1sn sık",
            videoUrl: "https://www.youtube.com/watch?v=283ZON11sIg", embeddable: true,
            sets: 3, dose: { type: "repRange", min: 10, max: 12 }, restSec: [60, 90],
            trackable: false, trackingPhase: null, ruleSetRef: null,
            untrackableReason: "Makinede oturuş + kol pedleri öklüzyonu." },
          { id: "incline-chest-press-m", name: "Incline Chest Press Machine",
            coachNote: "omuzlar geri-aşağı sabit",
            videoUrl: "https://www.youtube.com/watch?v=tg6L1x9FYTI", embeddable: true,
            sets: 3, dose: { type: "repRange", min: 8, max: 10 }, restSec: [60, 90],
            trackable: false, trackingPhase: null, ruleSetRef: null,
            untrackableReason: "Makineye yaslanmış oturuş — gövde landmark'ları örtülü." },
          { id: "flat-db-bench", name: "Flat Dumbbell Bench Press",
            coachNote: "kürekle çek, dirsek arkaya-yukarı",
            videoUrl: "https://www.youtube.com/watch?v=YQ2s_Y7g5Qk", embeddable: true,
            sets: 3, dose: { type: "repRange", min: 8, max: 10 }, restSec: [60, 90],
            trackable: false, trackingPhase: null, ruleSetRef: null,
            untrackableReason: "Bench'e sırtüstü yatış — pose modeli supine pozda güvenilmez." },
          { id: "chest-press-m", name: "Chest Press Machine",
            coachNote: null,
            videoUrl: "https://www.youtube.com/watch?v=piWs4q7R0ww", embeddable: true,
            sets: 3, dose: { type: "repRange", min: 10, max: 12 }, restSec: [60, 90],
            trackable: false, trackingPhase: null, ruleSetRef: null,
            untrackableReason: "Makinede oturuş + ekipman öklüzyonu." },
          { id: "db-row", name: "Dumbbell Row",
            coachNote: "kürekle çek, dirsek arkaya",
            videoUrl: "https://www.youtube.com/watch?v=scYLR0sO7yg", embeddable: true,
            sets: 3, dose: { type: "repRange", min: 10, max: 12 }, restSec: [60, 90],
            trackable: false, trackingPhase: null, ruleSetRef: null,
            untrackableReason: "Bench destekli eğilmiş poz — gövde/kol örtüşmesi dirsek yörüngesini gizler." },
          { id: "lat-pulldown", name: "Lat Pull Down",
            coachNote: "göğüs dışarı, dirsekler aşağı-arkaya",
            videoUrl: "https://www.youtube.com/watch?v=9ybzKMuIKNY", embeddable: true,
            sets: 3, dose: { type: "repRange", min: 12, max: 15 }, restSec: [60, 90],
            trackable: false, trackingPhase: null, ruleSetRef: null,
            untrackableReason: "Kablo istasyonunda oturuş + bar/kol öklüzyonu." },
        ]},
        { type: "stretch", label: "Esneme", exercises: [
          { id: "doorway-chest-stretch", name: "Doorway Chest Stretch", coachNote: null,
            videoUrl: "https://www.youtube.com/shorts/O8rJw_TmC1Y", embeddable: true,
            sets: 2, dose: { type: "timeRange", minSec: 30, maxSec: 40 },
            trackable: false, trackingPhase: null, ruleSetRef: null,
            untrackableReason: "Statik esneme — süre sayacı yeterli." },
          { id: "childs-pose-lat", name: "Child's Pose Lat Stretch", coachNote: null,
            videoUrl: "https://www.youtube.com/shorts/HkWppK_4C-8", embeddable: true,
            sets: 2, dose: { type: "timeRange", minSec: 30, maxSec: 40 },
            trackable: false, trackingPhase: null, ruleSetRef: null,
            untrackableReason: "Statik esneme — süre sayacı yeterli." },
          { id: "wall-lat-stretch", name: "Wall Lat Stretch", coachNote: null,
            videoUrl: "https://www.youtube.com/shorts/JUglskfkdgQ", embeddable: true,
            sets: 2, dose: { type: "timeRange", minSec: 30, maxSec: 40 },
            trackable: false, trackingPhase: null, ruleSetRef: null,
            untrackableReason: "Statik esneme — süre sayacı yeterli." },
        ]},
        plankFinisher("d2"),
      ],
    },
    // ─────────────── ANTRENMAN 3 — Perşembe ───────────────
    {
      id: "day3", label: "Antrenman 3", suggestedDay: "Perşembe",
      blocks: [
        { type: "warmup", label: "Isınma", exercises: [
          { id: "band-pull-apart-3", name: "Band Pull Apart", coachNote: null,
            videoUrl: "https://www.youtube.com/shorts/SuvO4TBwSu4", embeddable: true,
            sets: 1, dose: { type: "reps", value: 20 }, trackable: false, trackingPhase: null,
            ruleSetRef: null, untrackableReason: "Düşük genlikli bant hareketi." },
          { id: "arm-swings", name: "Arm Swings", coachNote: null,
            videoUrl: "https://www.youtube.com/watch?v=LVuNXZJg1DQ", embeddable: true,
            sets: 1, dose: { type: "reps", value: 20 }, trackable: false, trackingPhase: null,
            ruleSetRef: null, untrackableReason: "Serbest savurma — form kuralı anlamlı değil, sayım değeri düşük." },
          { id: "light-db-lateral", name: "Light DB Lateral Raise", coachNote: null,
            videoUrl: "https://www.youtube.com/watch?v=ureBK3Q0uEM", embeddable: true,
            sets: 1, dose: { type: "reps", value: 15 },
            trackable: true, trackingPhase: "P0", ruleSetRef: "lateralRaise", untrackableReason: null },
        ]},
        { type: "straight", label: "Ana Antrenman", exercises: [
          { id: "db-lateral-raise", name: "Dumbbell Lateral Raise",
            coachNote: "hafif çapraz yukarı",
            videoUrl: "https://www.youtube.com/watch?v=ureBK3Q0uEM", embeddable: true,
            sets: 3, dose: { type: "reps", value: 12 }, restSec: [60, 90],
            trackable: true, trackingPhase: "P0", ruleSetRef: "lateralRaise", untrackableReason: null },
          { id: "cable-lateral-raise", name: "Cable Lateral Raise",
            coachNote: null,
            videoUrl: "https://www.youtube.com/watch?v=rO3vuRvtxIo", embeddable: true,
            sets: 3, dose: { type: "repRange", min: 12, max: 15 }, restSec: [60, 90],
            trackable: false, trackingPhase: null, ruleSetRef: null,
            untrackableReason: "Kablo istasyonuna bitişik duruş — makine gövdeyi kısmen örter." },
          { id: "reverse-pec-deck", name: "Reverse Pec Deck",
            coachNote: "kürekleri sıkma, arka omuz izole",
            videoUrl: "https://www.youtube.com/watch?v=5YK4bgzXDp0", embeddable: true,
            sets: 3, dose: { type: "repRange", min: 12, max: 15 }, restSec: [60, 90],
            trackable: false, trackingPhase: null, ruleSetRef: null,
            untrackableReason: "Makineye yüzükoyun oturuş — gövde/omuz landmark'ları örtülü." },
          { id: "machine-shoulder-press", name: "Machine Shoulder Press",
            coachNote: "dirsek kulak hizasını biraz geçsin",
            videoUrl: "https://www.youtube.com/watch?v=WvLMauqrnK8", embeddable: true,
            sets: 3, dose: { type: "repRange", min: 10, max: 12 }, restSec: [60, 90],
            trackable: false, trackingPhase: null, ruleSetRef: null,
            untrackableReason: "Makinede oturuş + kol rayları öklüzyonu." },
          { id: "db-hammer-curl", name: "Dumbbell Hammer Curl",
            coachNote: "dirsek sabit, üstte 1sn",
            videoUrl: "https://www.youtube.com/watch?v=xX49MXefLWk", embeddable: true,
            sets: 4, dose: { type: "repRange", min: 10, max: 12 }, restSec: [60, 90],
            // "üstte 1sn" tutuş zaman katmanı motorda yok → form takibi rep + dirsek-sabit kuralı.
            trackable: true, trackingPhase: "P0", ruleSetRef: "hammerCurl", untrackableReason: null },
          { id: "rope-pushdown", name: "Rope Pushdown",
            coachNote: "altta ipi yanlara aç",
            videoUrl: "https://www.youtube.com/watch?v=iKespECqOdM", embeddable: true,
            sets: 3, dose: { type: "reps", value: 12 }, restSec: [60, 90],
            trackable: false, trackingPhase: null, ruleSetRef: null,
            untrackableReason: "Kablo istasyonuna yakın duruş; 'ipi yanlara aç' detayı el yönelimi landmark'ından ölçülemez." },
          { id: "overhead-db-triceps", name: "Overhead Dumbbell Triceps Extension",
            coachNote: "dirsekler içeri kapalı, negatif yavaş",
            videoUrl: "https://www.youtube.com/watch?v=N9WK3LgZjf4", embeddable: true,
            sets: 3, dose: { type: "reps", value: 12 }, restSec: [60, 90],
            trackable: false, trackingPhase: null, ruleSetRef: null,
            untrackableReason: "Dambıl baş arkasında — kol/baş öklüzyonu dirsek takibini bozar." },
        ]},
        { type: "stretch", label: "Esneme", exercises: [
          { id: "doorway-chest-stretch-3", name: "Doorway Chest Stretch", coachNote: null,
            videoUrl: "https://www.youtube.com/shorts/O8rJw_TmC1Y", embeddable: true,
            sets: 2, dose: { type: "timeRange", minSec: 30, maxSec: 40 },
            trackable: false, trackingPhase: null, ruleSetRef: null, untrackableReason: "Statik esneme." },
          { id: "childs-pose-lat-3", name: "Child's Pose Lat Stretch", coachNote: null,
            videoUrl: "https://www.youtube.com/shorts/HkWppK_4C-8", embeddable: true,
            sets: 2, dose: { type: "timeRange", minSec: 30, maxSec: 40 },
            trackable: false, trackingPhase: null, ruleSetRef: null, untrackableReason: "Statik esneme." },
          { id: "wall-shoulder-flexion", name: "Wall Shoulder Flexion Stretch", // ad video başlığından (PDF'te belirsiz)
            coachNote: null,
            videoUrl: "https://www.youtube.com/watch?v=YD8W4XK-Nv4", embeddable: true,
            sets: 2, dose: { type: "timeRange", minSec: 30, maxSec: 40 },
            trackable: false, trackingPhase: null, ruleSetRef: null, untrackableReason: "Statik esneme." },
        ]},
      ],
    },
    // ─────────────── ANTRENMAN 4 — Cumartesi ───────────────
    {
      id: "day4", label: "Antrenman 4", suggestedDay: "Cumartesi",
      blocks: [
        { type: "warmup", label: "Isınma", exercises: [
          // A1 ısınmasıyla aynı 4 hareket (jumping-jack, bw-squat-warmup, band-pull-apart, standing-knee-raise)
          { id: "jumping-jack-4", name: "Jumping Jack", coachNote: null,
            videoUrl: "https://www.youtube.com/watch?v=czMg1_idVcg", embeddable: true,
            sets: 1, dose: { type: "time", seconds: 45 },
            trackable: true, trackingPhase: "P0", ruleSetRef: "jumpingJack", untrackableReason: null },
          { id: "bw-squat-warmup-4", name: "Bodyweight Squat", coachNote: null,
            videoUrl: "https://www.youtube.com/watch?v=EdgOc-sbddA", embeddable: true,
            sets: 1, dose: { type: "reps", value: 15 },
            trackable: true, trackingPhase: "P0", ruleSetRef: "squat", untrackableReason: null },
          { id: "band-pull-apart-4", name: "Band Pull Apart", coachNote: null,
            videoUrl: "https://www.youtube.com/shorts/SuvO4TBwSu4", embeddable: true,
            sets: 1, dose: { type: "reps", value: 20 }, trackable: false, trackingPhase: null,
            ruleSetRef: null, untrackableReason: "Düşük genlikli bant hareketi." },
          { id: "standing-knee-raise-4", name: "Standing Knee Raise", coachNote: null,
            videoUrl: "https://www.youtube.com/watch?v=O_8EUJ7i-PI", embeddable: true,
            sets: 1, dose: { type: "perSide", value: 12 },
            trackable: true, trackingPhase: "P0", ruleSetRef: "kneeRaise", untrackableReason: null },
        ]},
        { type: "straight", label: "Ana Antrenman", exercises: [
          { id: "barbell-squat", name: "Squat",
            coachNote: "ayak 15-20° dışa, taban yere basılı, dizler içeri çökmesin",
            videoUrl: "https://www.youtube.com/watch?v=bljRUSOf_cs", embeddable: true,
            sets: 3, dose: { type: "repRange", min: 15, max: 20 }, restSec: [60, 90],
            trackable: true, trackingPhase: "P0", ruleSetRef: "squat", untrackableReason: null },
            // hoca notu eşlemesi: "dizler içeri çökmesin" → valgus kuralı; "taban yere basılı" → heel kuralı;
            // "ayak 15-20° dışa" → ölçülemez, ekran notu
          { id: "leg-press", name: "Leg Press",
            coachNote: "ayaklar çok aşağıda olmasın, kalça minderden kalkmasın",
            videoUrl: "https://www.youtube.com/watch?v=vChokSQ2roY", embeddable: true,
            sets: 3, dose: { type: "reps", value: 15 }, restSec: [60, 90],
            trackable: false, trackingPhase: null, ruleSetRef: null,
            untrackableReason: "Makinede yatık oturuş — gövde/kalça landmark'ları makine tarafından örtülür." },
          { id: "lying-leg-curl", name: "Lying Leg Curl",
            coachNote: "ayaklar içe, üstte 1sn",
            videoUrl: "https://www.youtube.com/watch?v=NgDeIu6zTVA", embeddable: true,
            sets: 3, dose: { type: "reps", value: 12 }, restSec: [60, 90],
            trackable: false, trackingPhase: null, ruleSetRef: null,
            untrackableReason: "Yüzüstü makine pozisyonu — pose modeli prone pozda güvenilmez." },
          { id: "leg-extension", name: "Leg Extension",
            coachNote: "dizleri kilitleme",
            videoUrl: "https://www.youtube.com/watch?v=Hf_X4dS-NNo", embeddable: true,
            sets: 3, dose: { type: "reps", value: 12 }, restSec: [60, 90],
            trackable: false, trackingPhase: null, ruleSetRef: null,
            untrackableReason: "Makinede oturuş + ped öklüzyonu." },
          { id: "hip-adduction", name: "Hip Adduction",
            coachNote: "negatif özellikle",
            videoUrl: "https://www.youtube.com/watch?v=lASGsXkOxpg", embeddable: true,
            sets: 3, dose: { type: "reps", value: 15 }, restSec: [60, 90],
            trackable: false, trackingPhase: null, ruleSetRef: null,
            untrackableReason: "Makinede oturuş — bacak pedleri ve gövde örtüşmesi." },
          { id: "hip-abduction", name: "Hip Abduction",
            coachNote: "negatif kontrollü",
            videoUrl: "https://www.youtube.com/watch?v=LT6_yNVfYAE", embeddable: true,
            sets: 3, dose: { type: "reps", value: 15 }, restSec: [60, 90],
            trackable: false, trackingPhase: null, ruleSetRef: null,
            untrackableReason: "Makinede oturuş — bacak pedleri ve gövde örtüşmesi." },
        ]},
        { type: "stretch", label: "Esneme", exercises: [
          { id: "quad-stretch", name: "Standing Quad Stretch", coachNote: null,
            videoUrl: "https://www.youtube.com/watch?v=TU2QkiQatWg", embeddable: true,
            sets: 2, dose: { type: "timeRange", minSec: 30, maxSec: 40 },
            trackable: false, trackingPhase: null, ruleSetRef: null, untrackableReason: "Statik esneme." },
          { id: "hamstring-stretch", name: "Standing Hamstring Stretch", coachNote: null,
            videoUrl: "https://www.youtube.com/watch?v=LLn2_W80ZYo", embeddable: true,
            sets: 2, dose: { type: "timeRange", minSec: 30, maxSec: 40 },
            trackable: false, trackingPhase: null, ruleSetRef: null, untrackableReason: "Statik esneme." },
          { id: "knee-to-chest-stretch", name: "Standing Knee to Chest Stretch", coachNote: null,
            videoUrl: "https://www.youtube.com/watch?v=HehpyuAkpZg", embeddable: true,
            sets: 2, dose: { type: "timeRange", minSec: 30, maxSec: 40 },
            trackable: false, trackingPhase: null, ruleSetRef: null, untrackableReason: "Statik esneme." },
        ]},
        plankFinisher("d4"),
      ],
    },
  ],
};
